version: "3.8"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  api:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

volumes:
  db:
    driver: local