version: "3.3"

services:
  database:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  api:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database

volumes:
  db:
    driver: local